#!/bin/sh
exec 2>&1
cd "/home/alfredo/Downloads/ursim-3.6.0.30512/GUI/felix-cache/bundle92/data/com/ur/urcap/profinet/impl/daemon/"
exec "/home/alfredo/Downloads/ursim-3.6.0.30512/GUI/felix-cache/bundle92/data/com/ur/urcap/profinet/impl/daemon/PN"
